name: Test, Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  jasmine_tests:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm install -g jasmine
      - run: jasmine init --esm
      - run: jasmine

  build_artifacts:
    runs-on: ubuntu-latest
    container: node:18
    needs: jasmine_tests

    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p build
          cp -r img js json styles.css index.html chat-bild.jpeg chat-img.jpeg group-img.jpeg build/
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  deploy_app:
    runs-on: ubuntu-latest
    container: node:18-alpine
    needs: build_artifacts

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      HETZNER_SERVER: ${{ secrets.HETZNER_SERVER }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      - run: apk add --no-cache openssh sshpass rsync

      - run: |
          sshpass -p "$SSH_PASSWORD" rsync -avz -e "ssh -p 222 -o StrictHostKeyChecking=no" \
          build/ "$SSH_USER@$HETZNER_SERVER:/usr/home/gjnnlo/public_html/apm25/"

      - run: |
          sshpass -p "$SSH_PASSWORD" ssh -p 222 -o StrictHostKeyChecking=no \
          "$SSH_USER@$HETZNER_SERVER" "cd /usr/home/gjnnlo/public_html/apm25/ || exit 1;"